from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = true
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"
pre_bump_hooks = ["echo '__version__ = \"{{version}}\"' > vasm/__version__.py"]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]
chore = { omit_from_changelog = true }
ci = { omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
authors = [
  { signature = "JiƒÅn", username = "coolDudeRude" },
  { signature = "Jian", username = "coolDudeRude" },
]

[bump_profiles]

[packages]
